/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_zlg_www_ControlCAN */

#ifndef _Included_cn_zlg_www_ControlCAN
#define _Included_cn_zlg_www_ControlCAN
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_zlg_www_ControlCAN
 * Method:    initTCPServer
 * Signature: (ILjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_zlg_www_ControlCAN_initTCPServer(JNIEnv *,
		jobject, jint, jstring, jint);

/*
 * Class:     cn_zlg_www_ControlCAN
 * Method:    initTCPClient
 * Signature: (Ljava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_zlg_www_ControlCAN_initTCPClient(JNIEnv *,
		jobject, jstring, jint, jint);

/*
 * Class:     cn_zlg_www_ControlCAN
 * Method:    initUDP
 * Signature: (ILjava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_zlg_www_ControlCAN_initUDP(JNIEnv *, jobject,
		jint, jstring, jint, jint);

/*
 * Class:     cn_zlg_www_ControlCAN
 * Method:    isConnected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cn_zlg_www_ControlCAN_isConnected(JNIEnv *,
		jobject);

/*
 * Class:     cn_zlg_www_ControlCAN
 * Method:    getReceiveNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_zlg_www_ControlCAN_getReceiveNum(JNIEnv *,
		jobject);

/*
 * Class:     cn_zlg_www_ControlCAN
 * Method:    recv
 * Signature: ([Lcn/zlg/www/FrmData;I)I
 */
JNIEXPORT jint JNICALL Java_cn_zlg_www_ControlCAN_recv(JNIEnv *, jobject,
		jobjectArray, jint);

/*
 * Class:     cn_zlg_www_ControlCAN
 * Method:    send
 * Signature: ([Lcn/zlg/www/FrmData;I)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_zlg_www_ControlCAN_send(JNIEnv *, jobject,
		jobjectArray, jint);

/*
 * Class:     cn_zlg_www_ControlCAN
 * Method:    readErrInfo
 * Signature: (Lcn/zlg/www/ErrData;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_zlg_www_ControlCAN_readErrInfo(JNIEnv *,
		jobject, jobject);

/*
 * Class:     cn_zlg_www_ControlCAN
 * Method:    clearBuffer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_zlg_www_ControlCAN_clearBuffer
(JNIEnv *, jobject);

/*
 * Class:     cn_zlg_www_ControlCAN
 * Method:    close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cn_zlg_www_ControlCAN_close(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
